FROM python

WORKDIR /home

COPY . .
# Install requirements
RUN pip install --no-cache-dir --upgrade pip
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables
ENV FLASK_APP=app.py

# ENTRYPOINT
ENTRYPOINT python app.py run